### ISSUE TITLE
请问有代码生成模块吗？

### ISSUE THREAD

**Issue by X-777** [wangxiang4/dolphin#1]

**Comment by wangxiang4** [comment]
目前还没有，最近这段时间工作上有点忙，基础部分的代码已经实现了 [表单设计器](https://github.com/wangxiang4/loquat-form-design) [还需要采用vue3+typescript进行重构]，后端表单生成器逻辑部分代码也已经实现了在公司内部使用暂时还不会进行开源，等待表单设计器重构完成会进行全部的一个整合测试稳定后再进行开源
